"""Assemble the block's result tables from the analysis files (no number is typed by hand).

File summary
- Path: research/dynamic_world_model/report.py
- Purpose: write `outputs/dynamic_world_model_20260926/analysis/report.md`, the tables the day record
  and the research README quote: data audit, registered primaries with their promotion verdicts,
  every policy, the provider arms, transition arms, card calibration, and the labelled post-hoc
  analyses (per-class time effect, naive reader, served-only episodes).
- Run: python research/dynamic_world_model/report.py (after episodes, dyn_model, transition,
  card_audit, agent_arms, repeatability, naive_reader and case_study)
- Depends on: common.py, analyze.py, episodes.py
"""
from __future__ import annotations

import json

import numpy as np
import pandas as pd

import analyze as A
import common as C
import episodes as E

OUT = C.OUTPUTS
ANALYSIS = OUT / "analysis"


def shown(action: str) -> str:
    """An action identifier as table text: its '|' separators would split a markdown cell."""
    return action.replace("|", " ")


def ci(d) -> str:
    return "n/a" if not d or d.get("mean") is None else f"{d['mean']:+.3f} [{d['low']:+.3f}, {d['high']:+.3f}]"


def rate(d) -> str:
    return "n/a" if not d or d.get("mean") is None else f"{d['mean']:.3f} [{d['low']:.3f}, {d['high']:.3f}]"


def per_class_time_table(data, protocol, detected) -> pd.DataFrame:
    magnitude = E.Magnitude(data, detected)
    rows = []
    for ctx, fold in E.contexts(data, protocol, detected, magnitude, tier_names=("A",)):
        for compound, truth, decoy, h1, h2 in E.episode_list(ctx, fold):
            for key in ctx.tier.keys:
                outcome = E.execute(ctx, compound, key, h1, h2)["outcome"]
                eliminated = {"eliminate_b": h2, "eliminate_a": h1}.get(outcome)
                rows.append({"class": truth, "compound": compound, "action": C.action_id(key),
                             "correct": float(eliminated == decoy)})
    frame = pd.DataFrame(rows)
    table = frame.pivot_table(index="class", columns="action", values="correct", aggfunc="mean")
    table["compounds"] = frame.groupby("class").compound.nunique()
    return table


def main() -> None:
    protocol = C.load_protocol()
    data = C.load()
    null = C.detection_null(data, protocol)
    detected = C.detected_flags(data, null)
    episodes = json.loads((ANALYSIS / "episode_summary.json").read_text(encoding="utf-8"))
    transition = json.loads((ANALYSIS / "transition_summary.json").read_text(encoding="utf-8"))
    perp = json.loads((ANALYSIS / "transition_posthoc_perp.json").read_text(encoding="utf-8"))
    cards = json.loads((OUT / "card_audit" / "summary.json").read_text(encoding="utf-8"))
    naive = json.loads((ANALYSIS / "naive_reader_posthoc.json").read_text(encoding="utf-8"))
    case = json.loads((OUT / "case_study" / "case_study.json").read_text(encoding="utf-8"))
    manifest = json.loads((OUT / "agent_arms" / "manifest.json").read_text(encoding="utf-8"))
    repeat_path = OUT / "agent_arms" / "repeatability.json"
    repeat = json.loads(repeat_path.read_text(encoding="utf-8")) if repeat_path.is_file() else None
    contrasts = {(c["tier"], c["a"], c["b"], c["metric"]): c for c in episodes["contrasts"]}
    lines = ["# Measurement choice for mechanism discrimination: generated results", "",
             "Generated by `research/dynamic_world_model/report.py` from the analysis files; intervals are 95%",
             "skeleton-clustered bootstrap (2,000 draws, seed 20260926). Post-hoc tables are labelled.", ""]

    # data audit
    counts = data.conditions.groupby(["time", "cell_line"]).size()
    lines += ["## Data audit", "", "| Time | Line | Conditions | QC-passed | Detected | Detection threshold (vehicle-well null q99, floor 0.10) | Null pairs |",
              "|---|---|---:|---:|---:|---:|---:|"]
    qc = np.array([C.qc_passed(data, i) for i in range(len(data.conditions))])
    for (t, line), n in counts.items():
        m = ((data.conditions.time == t) & (data.conditions.cell_line == line)).to_numpy()
        z = null[f"{line}|{t:g}"]
        lines.append(f"| {t:g} h | {line} | {n} | {int((qc & m).sum())} | {int((detected & m).sum())} | {z['threshold']:.3f} | {z['pairs']} |")
    lines += ["", "Cells are never observed twice; the 24 h and 72 h cohorts are different wells on different plates, paired by",
              "condition (compound, dose, line) only. Protein, morphology, chromatin and metabolism are not measured.", ""]

    # primaries
    p = {
        "P1": contrasts[("B", "separation", "magnitude", "correct")],
        "P2a": contrasts[("A", "dyn_ref", "magnitude", "correct")],
        "P2b": contrasts[("A", "dyn_ref", "fixed", "correct")],
        "P4": contrasts.get(("all", "deepseek_cards", "deepseek_base", "correct")),
    }
    p3 = transition["P3"]["difference_vs_persistence"]
    p5b = cards["B"]["T5"]["P5_multi_minus_single_logloss"]
    p5a = cards["A"]["T5"]["P5_multi_minus_single_logloss"]

    def verdict(d, positive=True):
        if not d or d.get("mean") is None:
            return "not run"
        if positive:
            return "met" if d["low"] > 0 else ("opposite direction" if d["high"] < 0 else "not demonstrated")
        return "met" if d["high"] < 0 else ("opposite direction" if d["low"] > 0 else "not demonstrated")

    lines += ["## Registered primary analyses", "", "| Analysis | Estimate | Verdict |", "|---|---|---|",
              f"| P1 tier B correct rate, separation minus magnitude | {ci(p['P1'])} | {verdict(p['P1'])} |",
              f"| P2 tier A correct rate, dyn_ref minus magnitude | {ci(p['P2a'])} | {verdict(p['P2a'])} |",
              f"| P2 tier A correct rate, dyn_ref minus fixed | {ci(p['P2b'])} | {verdict(p['P2b'])} |",
              f"| P3 T2 cosine, best learned arm ({transition['P3']['best_learned_arm']}) minus persistence (optimistic selection) | {ci(p3)} | {verdict(p3)} |",
              f"| P4 provider episodes (both tiers), deepseek_cards minus deepseek_base | {ci(p['P4'])} | {verdict(p['P4'])} |",
              f"| P5 tier B log loss, multi-branch minus single-mean | {ci(p5b)} | {verdict(p5b, positive=False)} |",
              f"| P5 tier A log loss, multi-branch minus single-mean | {ci(p5a)} | {verdict(p5a, positive=False)} |", ""]

    # policy table
    lines += ["## Every policy (registered episode set: tier B 2,160 contrasts, tier A 336)", "",
              (ANALYSIS / "episode_table.md").read_text(encoding="utf-8").strip(), ""]
    keep = [("B", "magnitude", "cost_only", "correct"), ("A", "magnitude", "cost_only", "correct"),
            ("B", "separation", "separation_permuted", "correct"), ("B", "separation", "magnitude", "wrong_any"),
            ("B", "separation", "magnitude", "utility"), ("A", "dyn_ref", "magnitude", "utility"),
            ("A", "dyn_model", "dyn_ref", "correct"), ("B", "dyn_model", "dyn_ref", "correct"),
            ("B", "separation", "fixed", "correct"), ("B", "separation", "random", "correct")]
    lines += ["| Secondary contrast | Estimate |", "|---|---|"]
    for k in keep:
        if k in contrasts:
            lines.append(f"| tier {k[0]} {k[3]}: {k[1]} minus {k[2]} | {ci(contrasts[k])} |")
    lines.append("")

    # provider arms
    lines += ["## Provider arms (one seeded contrast per held-out compound: tier B 135, tier A 42)", "",
              "| Tier | Arm | Correct | Wrong | minus magnitude | minus fixed | minus deepseek_base |", "|---|---|---|---|---|---|---|"]
    table = {(r["tier"], r["policy"]): r for r in episodes["rows"]}
    for tier in ("B", "A"):
        for arm in ("deepseek_base", "deepseek_cards", "deepseek_cards_permuted", "jev_cards", "jev_base"):
            if (tier, arm) not in table:
                continue
            r = table[(tier, arm)]
            lines.append(f"| {tier} | {arm} | {rate(r['correct'])} | {rate(r['wrong_elimination'])} | "
                         f"{ci(contrasts.get((tier, arm, 'magnitude', 'correct')))} | {ci(contrasts.get((tier, arm, 'fixed', 'correct')))} | "
                         f"{ci(contrasts.get((tier, arm, 'deepseek_base', 'correct')))} |")
    jev = {}
    for arm in ("jev_cards", "jev_base"):
        path = OUT / "agent_arms" / f"trace_{arm}.jsonl"
        if path.is_file():
            trace = [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines()]
            verdicts = pd.Series([t["answer"].get("verdict") for t in trace]).value_counts().to_dict()
            agreement = [t["answer"].get("agreement") for t in trace if t["answer"].get("agreement") is not None]
            jev[arm] = {"states": len(trace), "verdicts": verdicts, "mean_agreement": float(np.mean(agreement)) if agreement else None}
    lines += ["", f"Jev stability (eight repeats per state): {json.dumps(jev)}."]
    if repeat:
        lines.append(f"DeepSeek repeatability: {repeat['states']} first-step states asked four times in all; mean agreement "
                     f"{repeat['mean_agreement']:.3f}; all four answers identical in {repeat['all_four_identical']:.2f} of states.")
    ledger = json.loads((OUT / "agent_arms" / "deepseek_spend.json").read_text(encoding="utf-8"))
    jev_usage = json.loads((OUT / "agent_arms" / "jev_usage.json").read_text(encoding="utf-8"))
    lines += [f"Provider spend: DeepSeek ${ledger['total_usd']:.4f} in total: {ledger['calls']} ledger calls "
              f"(${ledger['session_total_usd']:.4f}) plus a declared carry-in of ${ledger['prior_total_usd']:.4f} "
              f"({ledger['prior_note']}); Jev {jev_usage['input_tokens_including_prior']} input tokens in total, "
              f"${jev_usage['usd_at_0.042_per_million']:.4f} at $0.042 per million.", ""]

    # transition
    lines += ["## Transition arms (held-out compounds, detected targets)", "",
              "| Family | Pairs | Replicate ceiling | Persistence cos | Gene ridge cos (minus persistence) | Retrieval k3 cos | Latent ridge cos | MLP cos | Nearest-template class correct: observed / persistence / gene ridge |",
              "|---|---:|---:|---:|---|---:|---:|---:|---|"]
    for name in ("T2_time", "T4_context", "dose_single_source"):
        s = transition[name]["detected_targets"]
        a = s["arms"]
        cls = (f"{s.get('observed_class_is_true_class', float('nan')):.3f} / {a['persistence'].get('class_is_true_class') or float('nan'):.3f} / "
               f"{a['gene_ridge'].get('class_is_true_class') or float('nan'):.3f}") if "observed_class_is_true_class" in s else "n/a"
        lines.append(f"| {name} | {s['pairs']} | {s['ceiling_cosine']:.3f} | {a['persistence']['cosine']['mean']:.3f} | "
                     f"{a['gene_ridge']['cosine']['mean']:.3f} ({ci(a['gene_ridge']['cosine_minus_persistence'])}) | "
                     f"{a['retrieval_k3']['cosine']['mean']:.3f} | {a['latent_ridge_residual']['cosine']['mean']:.3f} | "
                     f"{a['mlp_latent_residual']['cosine']['mean']:.3f} | {cls} |")
    for kind in ("interpolation", "extrapolation"):
        s = transition["T3_dose"][kind]
        a = s["arms"]
        lines.append(f"| T3 dose {kind} | {s['pairs']} | {s['ceiling_cosine']:.3f} | nearest {a['nearest_dose']['cosine']['mean']:.3f} | "
                     f"ridge {a['ridge_neighbours']['cosine']['mean']:.3f} ({ci(a['ridge_neighbours']['cosine_minus_nearest_dose'])}) | "
                     f"log-dose {a['log_dose_interpolation']['cosine']['mean']:.3f} | | | |")
    lines += ["", f"Post hoc, cosine after projecting out the target condition's shared training axis: {json.dumps(perp['detected_targets'])}.", ""]

    # cards
    lines += ["## Scenario-card calibration, refusals and T5 (every menu action scored against the real outcome)", "",
              "| Tier | Served fraction | Predicted / realised correct (served) | ECE served | Refused: realised correct | Shadow ECE on refused (one reference allowed) | Log loss multi-branch / single mean / pooled marginal |",
              "|---|---:|---|---:|---:|---:|---|"]
    for tier in ("B", "A"):
        d = cards[tier]
        t5 = d["T5"]
        lines.append(f"| {tier} | {d['served_fraction']:.3f} | {d['served']['mean_predicted']:.3f} / {d['served']['mean_realised']:.3f} | "
                     f"{d['served']['ece']:.3f} | {d['refused']['realised_correct_rate']:.3f} | {d['refused']['shadow_ece']:.3f} | "
                     f"{t5['logloss:multi_branch']:.3f} / {t5['logloss:single_mean']:.3f} / {t5['logloss:pooled_marginal']:.3f} |")
    lines += ["", "Log loss of the multi-branch card by number of references for the true hypothesis (tier B): "
              + "; ".join(f"{r['references']}: {r['logloss']:.3f} (n={r['n']})" for r in cards["B"]["T5"]["logloss_by_reference_count"]), ""]

    # post hoc
    lines += ["## Post-hoc analyses (labelled; not registered)", "",
              "Per-class correct-elimination rate for a single measurement, tier A (A549), all contrasts:", ""]
    pc = per_class_time_table(data, protocol, detected)
    cols = ["A549|024h|01000nM", "A549|024h|10000nM", "A549|072h|01000nM", "A549|072h|10000nM", "compounds"]
    lines += ["| Class | " + " | ".join(shown(c) for c in cols) + " |", "|---|" + "---:|" * len(cols)]
    for klass, r in pc.iterrows():
        lines.append(f"| {klass} | " + " | ".join(f"{r[c]:.2f}" if c != "compounds" else f"{int(r[c])}" for c in cols) + " |")
    lines += ["", "Validator against naive readers, per menu measurement (tier B / tier A):", "",
              "| Reader | Wrong elimination | Correct elimination |", "|---|---|---|",
              f"| registered validator | {rate(naive['B']['validator_wrong'])} / {rate(naive['A']['validator_wrong'])} | {rate(naive['B']['validator_correct'])} / {rate(naive['A']['validator_correct'])} |",
              f"| nearest class, no gates | {rate(naive['B']['naive_wrong'])} / {rate(naive['A']['naive_wrong'])} | {rate(naive['B']['naive_correct'])} / {rate(naive['A']['naive_correct'])} |",
              f"| absence read as \"perturbation failed\" (wrong whenever the compound is decisive elsewhere) | {rate(naive['B']['absence_misread'])} / {rate(naive['A']['absence_misread'])} | |", ""]

    # case study
    a = case["anchors"]
    lines += ["## Case study: DNA methyltransferase and PRC2 inhibitors against \"the perturbation failed\" (A549)", "",
              f"- Anchor 1 (weaker at 24 h than HDAC inhibitors): {'held' if a['anchor_1_weaker_at_24h'] else 'failed'}; "
              f"replicate agreement {json.dumps({k: round(v, 3) for k, v in a['summary_1uM_and_10uM']['agreement_24h'].items()})}, "
              f"shift norm {json.dumps({k: round(v, 2) for k, v in a['summary_1uM_and_10uM']['norm_24h'].items()})}.",
              f"- Anchor 2 (norm grows more to 72 h): {'held' if a['anchor_2_grows_more_to_72h'] else 'failed'}; ratios "
              f"{json.dumps({k: round(v, 3) for k, v in a['summary_1uM_and_10uM']['norm_ratio_72_over_24'].items()})}.",
              f"- Anchor 3 (DNA methyltransferase inhibitors raise interferon-alpha genes by 72 h in every condition): "
              f"{'held' if a['anchor_3_dnmt_ifn_alpha_rises'] else 'failed'}; differences {[round(v, 3) for v in a['anchor_3_differences']]}.",
              f"- Post hoc: replicate agreement at 72 h {json.dumps({k: round(v, 3) for k, v in a['summary_1uM_and_10uM']['posthoc_agreement_72h'].items()})}.", "",
              "| Compound | Planner | Rounds (action: validator outcome) | Decision | Case state |", "|---|---|---|---|---|"]
    for loop in case["loops"]:
        rounds = "; ".join(f"{shown(r['action'])}: {r['outcome']}" if r.get("action") else f"deferred ({r.get('deferred')})" for r in loop["rounds"])
        lines.append(f"| {loop['compound']} | {loop['planner']} | {rounds} | {loop['decision']} | {loop['final_case_state']} |")
    q = case["qc_failure_demo"]
    lines += ["", f"Explicit non-success: {q['compound']} at {shown(q['action'])} lost both wells ({q['execution_log']['quality']['reasons']}); "
              f"after import the case is `{q['case_state_after_import']}` and {q['spent_days']:g} days are charged.", ""]
    (ANALYSIS / "report.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
